const messages = [
  "Ula, jesteś moim promyczkiem słońca ☀️",
  "Twoje oczy są piękniejsze niż gwiazdy ✨",
  "Każdy dzień z Tobą to cud 🎁",
  "Twoje uśmiechy poprawiają mi humor 😄",
  "Uwielbiam sposób, w jaki się śmiejesz 😂",
  "Jesteś moją najlepszą przyjaciółką i miłością ❤️",
  "Nie mogę przestać o Tobie myśleć 💭",
  "Jesteś cudowna taka jaka jesteś 🌸",
  "Twoje serce jest najpiękniejsze na świecie 💖",
  "Jesteś dla mnie najważniejsza 💎",
  "Gdy Cię widzę, moje serce bije szybciej 💓",
  "Uwielbiam Twoje spojrzenie 😍",
  "Jesteś niesamowicie wyjątkowa 🌈",
  "Dziękuję, że jesteś w moim życiu 🙏",
  "Twoja obecność sprawia, że czuję się szczęśliwy 😊",
  "Jesteś najpiękniejszą dziewczyną na świecie 👸",
  "Chciałbym Cię przytulić właśnie teraz 🤗",
  "Twój głos jest jak muzyka dla moich uszu 🎶",
  "Jesteś dla mnie inspiracją 🌟",
  "Uwielbiam patrzeć na Ciebie 🥰",
  "Każdy dzień z Tobą jest lepszy 🌞",
  "Jesteś moim szczęściem 🍀",
  "Jesteś słodka jak cukierek 🍬",
  "Kocham Twoją energię ⚡",
  "Twoje oczy są hipnotyzujące 👁️👁️",
  "Twoje dobre serce mnie rozczula 💕",
  "Jesteś spełnieniem moich marzeń 🌠",
  "Twoja radość jest zaraźliwa 😃",
  "Uwielbiam Twój śmiech 😆",
  "Jesteś moim powodem do uśmiechu 😌",
  "Jesteś piękna bez względu na wszystko 🌷",
  "Dziękuję, że jesteś sobą 💗",
  "Twoje słowa zawsze mnie wspierają 💬",
  "Nie wyobrażam sobie życia bez Ciebie 💑",
  "Jesteś najlepszym, co mnie spotkało 🎈",
  "Uwielbiam każdą chwilę z Tobą 🕰️",
  "Twoja troskliwość mnie wzrusza 😇",
  "Jesteś wyjątkowa w każdym calu ✨",
  "Jesteś moją gwiazdką na niebie ⭐",
  "Uwielbiam Twoją wrażliwość 🦋",
  "Jesteś magiczna ✨",
  "Twoje oczy są jak dwa oceany 🌊",
  "Twoje serce jest pełne dobra ❤️",
  "Uwielbiam Twoją szczerość 💬",
  "Jesteś radością mojego życia 🎉",
  "Kocham, kiedy się śmiejesz 😂",
  "Twoje uśmiechy sprawiają, że się topię ☺️",
  "Jesteś jak promień słońca po deszczu 🌦️",
  "Każdy Twój gest mnie zachwyca 💫",
  "Uwielbiam Twoją odwagę 🦁",
  "Jesteś najcenniejszym skarbem 💎",
  "Jesteś moim powietrzem 🌬️",
  "Kocham Twoją czułość 🤍",
  "Jesteś moim wsparciem 🛡️",
  "Twoja obecność mnie uspokaja 🕊️",
  "Uwielbiam Twoją spontaniczność 🎈",
  "Jesteś moim marzeniem, które się spełniło 🌠",
  "Twoje spojrzenie mnie rozbraja 😍",
  "Jesteś absolutnie niesamowita 🌟",
  "Uwielbiam Cię za wszystko 💖",
  "Jesteś moją inspiracją do działania 🚀",
  "Twój śmiech to mój ulubiony dźwięk 🎶",
  "Uwielbiam Twoją delikatność 🌸",
  "Twoje serce jest wielkie jak ocean 🌊",
  "Jesteś piękna zarówno na zewnątrz, jak i wewnątrz 🌹",
  "Każdy Twój dotyk jest magiczny ✨",
  "Uwielbiam patrzeć na Ciebie, gdy jesteś skupiona 😌",
  "Jesteś dla mnie całym światem 🌍",
  "Twoje oczy są pełne ciepła 🔥",
  "Jesteś moją najlepszą decyzją ❤️",
  "Uwielbiam Twoje poczucie humoru 😄",
  "Jesteś tak niesamowicie wyjątkowa 🌈",
  "Twój głos koi moje myśli 🎵",
  "Jesteś osobą, którą chcę trzymać za rękę zawsze 🤝",
  "Uwielbiam Twoją wyrozumiałość 🤗",
  "Jesteś moją motywacją 💪",
  "Twój śmiech jest moim lekarstwem 🥰",
  "Uwielbiam Twój styl i sposób bycia 👑",
  "Jesteś moim powodem do szczęścia 🍀",
  "Twoje spojrzenie mówi więcej niż tysiąc słów 👀",
  "Jesteś cudowna bez żadnych wątpliwości 💗",
  "Uwielbiam, jak się uśmiechasz rano 🌅",
  "Jesteś najpiękniejszą osobą, jaką znam 🌸",
  "Uwielbiam Twoją radość życia 🌞",
  "Twoje ciepło jest bezcenne 🔥",
  "Jesteś moim światłem w ciemności 🌌",
  "Uwielbiam Cię za wszystko, czym jesteś ❤️",
  "Jesteś aniołem w ludzkiej postaci 👼",
  "Twój uśmiech to magia ✨",
  "Uwielbiam słuchać Twoich opowieści 📖",
  "Jesteś moją najpiękniejszą historią 📜",
  "Twoje oczy mają w sobie coś niesamowitego 🌠",
  "Uwielbiam Twoje pomysły i marzenia 💭",
  "Jesteś osobą, którą chcę kochać do końca życia 💍",
  "Twoje dobroć mnie wzrusza 💞",
  "Uwielbiam każdą rozmowę z Tobą 🗨️",
  "Jesteś najważniejszą osobą w moim życiu 💓",
  "Uwielbiam Twoje ciepłe spojrzenie 😇",
  "Jesteś piękna w każdej sytuacji 🌹",
  "Uwielbiam Twoją wrażliwość na świat 🌍",
  "Jesteś moją najlepszą inspiracją 🌟",
  "Uwielbiam, jak się do mnie przytulasz 🤗",
  "Jesteś osobą pełną magii ✨",
  "Uwielbiam każdą chwilę z Tobą 🕰️",
  "Jesteś moim szczęściem każdego dnia ☀️",
  "Uwielbiam Twoje serce 💖",
  "Jesteś wyjątkowa i jedyna w swoim rodzaju 🌈",
  "Uwielbiam Twoje pasje i zainteresowania 🎨",
  "Jesteś moją codzienną radością 🌞",
  "Uwielbiam Twoją czułość 🤍",
  "Jesteś dla mnie najcenniejszym skarbem 💎",
  "Uwielbiam Twoją naturalność 🌿",
  "Jesteś powodem mojego uśmiechu 😁",
  "Uwielbiam Twoje dobre serce 💗",
  "Jesteś wszystkim, czego potrzebuję ❤️",
  "Uwielbiam każdą Twoją wiadomość 📲",
  "Jesteś moim spełnionym marzeniem 🌠",
  "Uwielbiam patrzeć, jak się śmiejesz 😂",
  "Jesteś moją największą radością 🎉",
  "Uwielbiam Twoje oczy pełne ciepła 🥰",
  "Jesteś moim słońcem po burzy 🌤️",
  "Uwielbiam każdą minutę spędzoną z Tobą ⏳",
  "Jesteś dla mnie wszystkim, co najpiękniejsze 🌺",
  "Uwielbiam Cię taką, jaka jesteś 🌸",
  "Jesteś absolutnie wyjątkowa i niezastąpiona 💖"
];

// Wyświetlanie wiadomości na podstawie godziny:
let index = parseInt(localStorage.getItem('msgIndex')) || 0;

function showMessage() {
  const container = document.getElementById('message');
  container.textContent = messages[index % messages.length];
  index++;
  localStorage.setItem('msgIndex', index);
}

// Start: wyświetl od razu
showMessage();

// Zaplanuj zmianę co godzinę
const msTillNextHour = (60 - new Date().getMinutes()) * 60 * 1000 - new Date().getSeconds() * 1000;
setTimeout(() => {
  showMessage();
  setInterval(showMessage, 60 * 60 * 1000);
}, msTillNextHour);
